apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels: 
    app: mypod
spec:
  containers: 
    - name: mypod
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb
spec: 
  type: LoadBalancer  
  selector:
    app: mypod
  ports:
    - name: http
      port: 80
      targetPort: 80
