apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-helloworld-rs
  labels:
    app: my-helloworld
  spec:
    replicas: 3
    selector:
      matchLables:
        app: my-helloworld
    template:
      metadata:
        lables:
          app: my-helloworld
      spec:
        containers:
        - name: my-helloworld-app
        image: hello-world
        