apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: LRS
  kind: managed